## Лабораторная работа №3. Обучение с учителем. Деревья решений и их ансамбли.

### (1) IEEE-CIS Fraud Detection — задача бинарной классификации мошеннических онлайн-транзакций.

### 1. Импорт библиотек

Нам понадобятся библиотеки для работы с файловой системой ВМ, загрузки, просмотра и обработки датасетов, а также обучения модели классификации.

In [14]:
# работа с файловой системой
import os

# чистка traceback
import warnings
warnings.filterwarnings(
    "ignore",
    category=FutureWarning
)
warnings.filterwarnings(
    "ignore",
    category=UserWarning
)

# работа с датасетами как с массивами и таблицами
import numpy as np
import pandas as pd

# предварительная обработка данных в датасетах
from sklearn.base import BaseEstimator, TransformerMixin, ClassifierMixin
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from feature_engine.encoding import CountFrequencyEncoder

# пользовательские трансформеры
from custom_transformers import OutlierClipper, CyclicalTimeEncoder

# написание своих деревьев решений
from dataclasses import dataclass
from typing import Optional, Union

# параллельное обучение деревьев
from joblib import Parallel, delayed

# готовые деревья решений из sklearn
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier as SkBaggingClassifier, RandomForestClassifier as SkRandomForestClassifier

# готовый градиентный бустинг из sklearn, XGBoost, LightGBM и CatBoost
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

# оценка точности предсказаний модели
from sklearn.metrics import accuracy_score, f1_score, classification_report

# перенос пайплайна fraud_pipeline.joblib и колонок fraud_processed_columns.joblib из ЛР1
import joblib

# запись результатов экспериментов в Google Sheet
import json
import gspread
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials

### 2. Загрузка и применение пайплайна предобработки данных из ЛР1

Сначала узнаем, как называются файлы в датасете, найдем нужный нам файл с данными для обучения и посмотрим, как он выглядит в общих чертах.

In [2]:
# путь к датасету согласно документации Yandex Cloud
dataset_path = "/home/jupyter/datasets/ieee-fraud-detection"

# список всех файлов в датасете
print("Файлы в датасете:")
print(os.listdir(dataset_path))

# путь к train_public
file_path = os.path.join(dataset_path, "train_public.csv")
# загрузка csv-файла
df = pd.read_csv(file_path)

# первые 5 строк
print("\nНабор тренировочных данных:")
df.head()

Файлы в датасете:
['train_public.csv', 'test_public.csv', 'sample_submission.csv']

Набор тренировочных данных:

   TransactionID  isFraud  ...  DeviceType                     DeviceInfo
0        2987000        0  ...         NaN                            NaN
1        2987001        0  ...         NaN                            NaN
2        2987002        0  ...         NaN                            NaN
3        2987003        0  ...         NaN                            NaN
4        2987004        0  ...      mobile  SAMSUNG SM-G892A Build/NRD90M

[5 rows x 434 columns]

Разделим train_public на данные для обучения и для тестирования модели машинного обучения. Обработаем получившиеся два массива данных по отдельности пайплайном из ЛР1.

In [3]:
# постоянный сид для воспроизводимости результатов
seed = 8

# разделение train_public на признаки и целевую переменную isFraud
X = df.drop(columns=["isFraud"])
y = df["isFraud"]

# разделение train_public на train data и test data
X_tr, X_te, y_tr, y_te = train_test_split(
    X,
    y,
    test_size=0.1,
    random_state=seed,
    stratify=y  # для несбалансированных данных в ieee-fraud-detection
)

# загрузка пайплайна и имен колонок
pipeline = joblib.load("fraud_pipeline.joblib")
processed_columns = joblib.load("fraud_processed_columns.joblib")

# предобработка данных пайплайном
X_tr_processed = pipeline.transform(X_tr)
X_te_processed = pipeline.transform(X_te)

### 3. Реализация BaggingClassifier и RandomForestClassifier в виде sklearn-совместимых классов

Базовый алгоритм для ансамблей - бинарное дерево решений на критерии энтропии Шеннона.

In [4]:
# Узел дерева решений. Может быть либо листом, либо внутренним узлом.
@dataclass
class _ClassificationNode:
    is_leaf: bool  # флаг: является ли узел листом
    prediction: Optional[int] = None  # предсказанный класс (для листа)
    proba: Optional[np.ndarray] = None  # вероятности классов (для листа)
    feature_index: Optional[int] = None  # индекс признака для сплита (для внутреннего узла)
    threshold: Optional[float] = None  # порог разбиения
    left: Optional["_ClassificationNode"] = None  # левый потомок (<= threshold)
    right: Optional["_ClassificationNode"] = None  # правый потомок (> threshold)

# Простая реализация дерева решений для бинарной классификации
class SimpleDecisionTreeClassifier(BaseEstimator, ClassifierMixin):

    def __init__(
    self,
    max_depth: Optional[int] = None,
    min_samples_split: int = 2,
    min_samples_leaf: int = 1,
    min_impurity_decrease: float = 0.0,
    max_thresholds: int = 512,
    max_features: Optional[Union[int, float, None]] = None,
    random_state: Optional[int] = None):
        # сохраняем гиперпараметры модели
        self.max_depth = max_depth
        self.min_samples_split = min_samples_split
        self.min_samples_leaf = min_samples_leaf
        self.min_impurity_decrease = min_impurity_decrease
        self.max_thresholds = max_thresholds
        self.max_features = max_features
        self.random_state = random_state
    
    # Считает энтропию Шеннона для массива меток y
    def _entropy(self, y: np.ndarray) -> float:
        # используется как мера классовой "нечистоты" узла
        if y.size == 0:
            return 0.0  # пустой набор → нулевая энтропия

        # считаем количество объектов каждого класса
        counts = np.bincount(y, minlength=self.n_classes_).astype(float)
        probs = counts / counts.sum()  # переводим в вероятности

        # убираем нули, чтобы избежать log2(0)
        probs = probs[probs > 0]
        return -np.sum(probs * np.log2(probs))

    # Создаёт листовой узел: считает вероятности классов и предсказание
    def _leaf(self, y: np.ndarray) -> _ClassificationNode:
        counts = np.bincount(y, minlength=self.n_classes_).astype(float)
        proba = counts / counts.sum()  # распределение классов
        prediction = int(np.argmax(proba))  # самый вероятный класс

        return _ClassificationNode(is_leaf=True, prediction=prediction, proba=proba)

    # Определяет, сколько признаков использовать при поиске сплита
    def _resolve_max_features(self, n_features: int) -> int:
        mf = self.max_features
        if mf is None:
            return n_features  # используем все признаки
        if isinstance(mf, int):
            if mf <= 0:
                raise ValueError("max_features as int must be >= 1.")
            return min(mf, n_features)  # не больше общего числа
        if isinstance(mf, float):
            if not (0.0 < mf <= 1.0):
                raise ValueError("max_features as float must be in (0, 1].")
            return max(1, int(np.ceil(mf * n_features))) # берём долю признаков
        raise ValueError("Unsupported type for max_features.")

    # Выбирает случайное подмножество признаков для сплита
    def _feature_indices_for_split(self, n_features: int) -> np.ndarray:
        k = self._resolve_max_features(n_features)

        if k == n_features:
            return np.arange(n_features)  # все признаки

        # случайная выборка без возвращения
        return self._rng.choice(n_features, size=k, replace=False)

    # Ищет лучший сплит по всем выбранным признакам и порогам
    def _best_split(self, X: np.ndarray, y: np.ndarray):

        n_samples, n_features = X.shape
        parent_impurity = self._entropy(y)  # энтропия родительского узла
        best = None  # сюда запишем лучший вариант (impurity, feature, threshold)

        feature_indices = self._feature_indices_for_split(n_features)

        # перебираем признаки
        for j in feature_indices:
            xj = X[:, j]

            # сортируем по возрастанию значения признака и соответствующие метки
            order = np.argsort(xj)
            x_sorted = xj[order]
            y_sorted = y[order]

            uniq = np.unique(x_sorted)
            if uniq.size < 2:
                continue  # нет смысла делить, все значения одинаковые

            # генерация кандидатов порогов
            if uniq.size > self.max_thresholds + 1:
                # слишком много уникальных значений → слишком много порогов, ограничиваем их числом max_thresholds порогов
                qs = np.linspace(0, 1, self.max_thresholds + 2)[1:-1] # равномерное разбиение на доли единицы ограниченным числом порогов
                thresholds = np.quantile(x_sorted, qs) # в качестве порогов берём значения признака на полученных выше квантилях
                thresholds = np.unique(thresholds) # убираем дубликаты
            else:
                # в качестве порогов берём середины между соседними значениями
                thresholds = (uniq[:-1] + uniq[1:]) / 2.0

            # проверяем каждый порог
            for t in thresholds:
                left_mask = x_sorted <= t
                right_mask = ~left_mask

                n_left = int(left_mask.sum())
                n_right = n_samples - n_left

                # проверка ограничения на минимальный размер листа
                if n_left < self.min_samples_leaf or n_right < self.min_samples_leaf:
                    continue

                y_left = y_sorted[left_mask]
                y_right = y_sorted[right_mask]

                # считаем энтропии детей
                h_left = self._entropy(y_left)
                h_right = self._entropy(y_right)

                # взвешенная энтропия после разбиения
                weighted_impurity = (
                    (n_left / n_samples) * h_left +
                    (n_right / n_samples) * h_right
                )

                # сохраняем лучший (минимальная impurity)
                if best is None or weighted_impurity < best[0]:
                    best = (weighted_impurity, j, t)

        return best, parent_impurity

    # Проверяет условия остановки роста дерева
    def _should_stop(self, X: np.ndarray, y: np.ndarray, depth: int) -> bool:
        if self.max_depth is not None and depth >= self.max_depth:
            return True  # достигли максимальной глубины
        if X.shape[0] < self.min_samples_split:
            return True  # слишком мало объектов
        if np.unique(y).size == 1:
            return True  # все объекты одного класса
        return False

    # Рекурсивно строит дерево
    def _build(self, X: np.ndarray, y: np.ndarray, depth: int) -> _ClassificationNode:

        if self._should_stop(X, y, depth):
            return self._leaf(y)

        best, parent_impurity = self._best_split(X, y)

        if best is None:
            return self._leaf(y)  # не нашли хороший сплит

        child_impurity, j, t = best
        improvement = parent_impurity - child_impurity

        # проверка минимального улучшения
        if improvement < self.min_impurity_decrease: # если улучшение разбиения слишком маленькое, то не делаем сплит
            return self._leaf(y)

        # делим данные
        left_mask = X[:, j] <= t
        right_mask = ~left_mask

        # рекурсивно строим поддеревья
        left = self._build(X[left_mask], y[left_mask], depth + 1)
        right = self._build(X[right_mask], y[right_mask], depth + 1)

        # создаём внутренний узел
        return _ClassificationNode(
            is_leaf=False,
            feature_index=j,
            threshold=t,
            left=left,
            right=right,
        )
    
    # Обучение дерева
    def fit(self, X, y):

        X = np.asarray(X)
        y = np.asarray(y)

        # кодируем классы в числа (0 и 1)
        self.classes_, y_encoded = np.unique(y, return_inverse=True)

        # ограничение: только бинарная классификация
        if self.classes_.shape[0] != 2:
            raise ValueError("This implementation supports only binary classification.")

        self.n_classes_ = len(self.classes_)
        self.n_features_in_ = X.shape[1]

        # генератор случайных чисел
        self._rng = np.random.RandomState(self.random_state)

        # строим дерево
        self.root_ = self._build(X, y_encoded, depth=0)

        return self

    # Проходит по дереву от корня до листа для одного объекта
    def _predict_proba_row(self, node: _ClassificationNode, x: np.ndarray) -> np.ndarray:
        while not node.is_leaf:
            if x[node.feature_index] <= node.threshold:
                node = node.left
            else:
                node = node.right
        return node.proba  # возвращаем вероятности из листа

    # Предсказание вероятностей для всех объектов
    def predict_proba(self, X):
        X = np.asarray(X)
        proba = np.array([self._predict_proba_row(self.root_, x) for x in X])
        return proba

    # Предсказание классов (argmax по вероятностям)
    def predict(self, X):
        proba = self.predict_proba(X)
        pred_idx = np.argmax(proba, axis=1)
        return self.classes_[pred_idx]

Bagging Classifier - ансамбль бинарных решающих деревьев на бутстрапе.

In [5]:
# Ансамбль деревьев решений (bagging)
# Каждое дерево обучается на случайной подвыборке, итог - усреднение предсказаний
class BaggingClassifier(BaseEstimator, ClassifierMixin):

    def __init__(
        self,
        n_estimators: int = 10,
        max_depth: Optional[int] = None,
        min_samples_split: int = 2,
        min_samples_leaf: int = 1,
        min_impurity_decrease: float = 0.0,
        max_thresholds: int = 512,
        bootstrap: bool = True,
        max_samples: Union[int, float] = 1.0,
        n_jobs: int = 1,
        random_state: Optional[int] = None,
    ):
        # сохраняем гиперпараметры ансамбля и базового дерева
        self.n_estimators = n_estimators
        self.max_depth = max_depth
        self.min_samples_split = min_samples_split
        self.min_samples_leaf = min_samples_leaf
        self.min_impurity_decrease = min_impurity_decrease
        self.max_thresholds = max_thresholds
        self.bootstrap = bootstrap
        self.max_samples = max_samples
        self.n_jobs = n_jobs
        self.random_state = random_state

    # Определяет размер подвыборки:
    def _resolve_sample_size(self, n_samples: int) -> int:
        if isinstance(self.max_samples, float):
            if not (0.0 < self.max_samples <= 1.0):
                raise ValueError("max_samples as float must be in (0, 1].")
            return max(1, int(self.max_samples * n_samples)) # берём долю объектов
        if isinstance(self.max_samples, int):
            if self.max_samples <= 0:
                raise ValueError("max_samples as int must be >= 1.")
            return min(self.max_samples, n_samples) # не больше общего числа объектов
        raise ValueError("max_samples must be int or float.")

    # Обучает одно дерево на случайной подвыборке
    def _fit_single_estimator(self, X: np.ndarray, y: np.ndarray, seed: int):

        rng = np.random.RandomState(seed)
        n_samples = X.shape[0]
        sample_size = self._resolve_sample_size(n_samples)

        # случайная выборка индексов (с повторением или без)
        indices = rng.choice(
            n_samples,
            size=sample_size,
            replace=self.bootstrap
        )

        X_boot = X[indices]
        y_boot = y[indices]

        # базовый алгоритм - обычное дерево
        tree = SimpleDecisionTreeClassifier(
            max_depth=self.max_depth,
            min_samples_split=self.min_samples_split,
            min_samples_leaf=self.min_samples_leaf,
            min_impurity_decrease=self.min_impurity_decrease,
            max_thresholds=self.max_thresholds,
            max_features=None,  # в bagging используем все признаки
            random_state=seed,
        )

        tree.fit(X_boot, y_boot)
        return tree

    # Обучает ансамбль
    def fit(self, X, y):

        X = np.asarray(X)
        y = np.asarray(y)

        # сохраняем исходные классы
        self.classes_, _ = np.unique(y, return_inverse=True)

        # ограничение: только бинарная классификация
        if self.classes_.shape[0] != 2:
            raise ValueError("This implementation supports only binary classification.")

        self.n_features_in_ = X.shape[1]

        # отдельный seed для каждого дерева
        rng = np.random.RandomState(self.random_state)
        seeds = rng.randint(0, 10**9, size=self.n_estimators)

        # параллельное обучение
        self.estimators_ = Parallel(n_jobs=self.n_jobs)(
            delayed(self._fit_single_estimator)(X, y, seed)
            for seed in seeds
        )

        return self

    # Каждое дерево даёт вероятности → усредняем
    def predict_proba(self, X):
        X = np.asarray(X)
        all_probas = np.array([
            est.predict_proba(X)
            for est in self.estimators_
        ])
        return np.mean(all_probas, axis=0)

    # Предсказание классов (по вероятности положительного)
    def predict(self, X, threshold: float = 0.5):
        proba_pos = self.predict_proba(X)[:, 1]
        pred = (proba_pos >= threshold).astype(int)
        return self.classes_[pred]

Random Forest Classifier - ансамбль бинарных решающих деревьев на бутстрапе c выбором n из всех N признаков.

In [6]:
# Ансамбль деревьев решений (random forest)
# Каждое дерево обучается на случайной подвыборке объектов, а при каждом сплите рассматривает только случайное подмножество признаков
class RandomForestClassifier(BaseEstimator, ClassifierMixin):
 
    def __init__(
        self,
        n_estimators: int = 10,
        max_depth: Optional[int] = None,
        min_samples_split: int = 2,
        min_samples_leaf: int = 1,
        min_impurity_decrease: float = 0.0,
        max_thresholds: int = 512,
        max_features: Optional[Union[int, float, None]] = 0.5,
        bootstrap: bool = True,
        max_samples: Union[int, float] = 1.0,
        n_jobs: int = 1,
        random_state: Optional[int] = None,
    ):
        # сохраняем гиперпараметры ансамбля и базового дерева
        self.n_estimators = n_estimators
        self.max_depth = max_depth
        self.min_samples_split = min_samples_split
        self.min_samples_leaf = min_samples_leaf
        self.min_impurity_decrease = min_impurity_decrease
        self.max_thresholds = max_thresholds
        self.max_features = max_features
        self.bootstrap = bootstrap
        self.max_samples = max_samples
        self.n_jobs = n_jobs
        self.random_state = random_state
 
    # Определяет размер подвыборки
    def _resolve_sample_size(self, n_samples: int) -> int:
        if isinstance(self.max_samples, float):
            if not (0.0 < self.max_samples <= 1.0):
                raise ValueError("max_samples as float must be in (0, 1].")
            return max(1, int(self.max_samples * n_samples))  # берём долю объектов
        if isinstance(self.max_samples, int):
            if self.max_samples <= 0:
                raise ValueError("max_samples as int must be >= 1.")
            return min(self.max_samples, n_samples)  # не больше общего числа объектов
 
        raise ValueError("max_samples must be int or float.")
 
    # Обучает одно дерево на случайной подвыборке
    def _fit_single_estimator(self, X: np.ndarray, y: np.ndarray, seed: int):
        rng = np.random.RandomState(seed)
        n_samples = X.shape[0]
        sample_size = self._resolve_sample_size(n_samples)
 
        # случайная выборка индексов (с повторением или без)
        indices = rng.choice(
            n_samples,
            size=sample_size,
            replace=self.bootstrap
        )
 
        X_boot = X[indices]
        y_boot = y[indices]
 
        # базовый алгоритм - дерево со случайным подмножеством признаков при сплитах
        tree = SimpleDecisionTreeClassifier(
            max_depth=self.max_depth,
            min_samples_split=self.min_samples_split,
            min_samples_leaf=self.min_samples_leaf,
            min_impurity_decrease=self.min_impurity_decrease,
            max_thresholds=self.max_thresholds,
            max_features=self.max_features,  # главное отличие random forest от bagging
            random_state=seed,
        )
 
        tree.fit(X_boot, y_boot)
        return tree
 
    # Обучает ансамбль
    def fit(self, X, y):
        
        X = np.asarray(X)
        y = np.asarray(y)
 
        # сохраняем исходные классы
        self.classes_, _ = np.unique(y, return_inverse=True)
 
        # ограничение: только бинарная классификация
        if self.classes_.shape[0] != 2:
            raise ValueError("This implementation supports only binary classification.")
 
        self.n_features_in_ = X.shape[1]
 
        # отдельный seed для каждого дерева
        rng = np.random.RandomState(self.random_state)
        seeds = rng.randint(0, 10**9, size=self.n_estimators)
 
        # параллельное обучение
        self.estimators_ = Parallel(n_jobs=self.n_jobs)(
            delayed(self._fit_single_estimator)(X, y, seed)
            for seed in seeds
        )
 
        return self
 
    # Каждое дерево даёт вероятности → усредняем
    def predict_proba(self, X):
        X = np.asarray(X)
        all_probas = np.array([
            est.predict_proba(X)
            for est in self.estimators_
        ])
        return np.mean(all_probas, axis=0)
 
    # Предсказание классов (по вероятности положительного)
    def predict(self, X, threshold: float = 0.5):
        proba_pos = self.predict_proba(X)[:, 1]
        pred = (proba_pos >= threshold).astype(int)
        return self.classes_[pred]

Для корректировки параметров сначала оценим качество предсказаний одного дерева.

In [7]:
sdt = SimpleDecisionTreeClassifier(max_depth=8, min_samples_split=30, min_samples_leaf=15, max_thresholds=512, random_state=seed).fit(X_tr_processed, y_tr)
y_pred_sdt = sdt.predict(X_te_processed)

print("accuracy:", accuracy_score(y_te, y_pred_sdt))
print(classification_report(y_te, y_pred_sdt, target_names=["not fraud", "fraud"]))

accuracy: 0.9740707814748962
              precision    recall  f1-score   support

   not fraud       0.98      1.00      0.99     45584
       fraud       0.83      0.33      0.47      1660

    accuracy                           0.97     47244
   macro avg       0.90      0.66      0.73     47244
weighted avg       0.97      0.97      0.97     47244

Даже у одного решающего дерева с умеренными параметрами для fraud f1-score = 0.47, что уже выше, чем у линейных моделей с их лучшими порогами.

С теми же параметрами обучим наш Bagging Classifier на train data, предскажем значения для test data и оценим результаты.

In [8]:
bc = BaggingClassifier(n_estimators=5, max_depth=8, min_samples_split=30, min_samples_leaf=15, max_thresholds=512, n_jobs=32, random_state=seed).fit(X_tr_processed, y_tr)
y_pred_bc = bc.predict(X_te_processed)

print("accuracy:", accuracy_score(y_te, y_pred_bc))
print(classification_report(y_te, y_pred_bc, target_names=["not fraud", "fraud"]))

accuracy: 0.9749597832528999
              precision    recall  f1-score   support

   not fraud       0.98      1.00      0.99     45584
       fraud       0.88      0.33      0.48      1660

    accuracy                           0.97     47244
   macro avg       0.93      0.67      0.74     47244
weighted avg       0.97      0.97      0.97     47244

У ансамбля из пяти решающих деревьев результаты чуть лучше, чем у одного дерева - f1-score = 0.48 для fraud за счет увеличения precision.

С теми же параметрами обучим наш Random Forest Classifier на train data, предскажем значения для test data и оценим результаты.

In [9]:
rfc = RandomForestClassifier(n_estimators=5, max_depth=8, min_samples_split=30, min_samples_leaf=15, max_thresholds=512, max_features=0.15, n_jobs=32, random_state=seed).fit(X_tr_processed, y_tr)
y_pred_rfc = rfc.predict(X_te_processed)

print("accuracy:", accuracy_score(y_te, y_pred_rfc))
print(classification_report(y_te, y_pred_rfc, target_names=["not fraud", "fraud"]))

accuracy: 0.9740496147658962
              precision    recall  f1-score   support

   not fraud       0.97      1.00      0.99     45584
       fraud       0.90      0.29      0.44      1660

    accuracy                           0.97     47244
   macro avg       0.94      0.65      0.71     47244
weighted avg       0.97      0.97      0.97     47244

Вырезание признаков в алгоритме Random Forest увеличило precision, но уменьшило recall.

### 4. Сравнение собственных реализаций с готовыми реализациями ансамблевых алгоритмов из sklearn

С теми же параметрами обучим готовый Bagging Classifier из sklearn на train data, предскажем значения для test data и оценим результаты.

In [15]:
bc_sk = SkBaggingClassifier(DecisionTreeClassifier(criterion='entropy', max_depth=8, min_samples_split=30, min_samples_leaf=15, random_state=seed),
                          n_estimators=5, n_jobs=32, random_state=seed).fit(X_tr_processed, y_tr)
y_pred_bc_sk = bc_sk.predict(X_te_processed)

print("accuracy:", accuracy_score(y_te, y_pred_bc_sk))
print(classification_report(y_te, y_pred_bc_sk, target_names=["not fraud", "fraud"]))

accuracy: 0.9746846160358987
              precision    recall  f1-score   support

   not fraud       0.98      1.00      0.99     45584
       fraud       0.90      0.32      0.47      1660

    accuracy                           0.97     47244
   macro avg       0.94      0.66      0.73     47244
weighted avg       0.97      0.97      0.97     47244

С теми же параметрами обучим готовый Random Forest Classifier из sklearn на train data, предскажем значения для test data и оценим результаты.

In [16]:
rfc_sk = SkRandomForestClassifier(n_estimators=5, criterion='entropy', max_depth=8, min_samples_split=30, min_samples_leaf=15, max_features=65, n_jobs=32, random_state=seed).fit(X_tr_processed, y_tr)
y_pred_rfc_sk = rfc_sk.predict(X_te_processed)

print("accuracy:", accuracy_score(y_te, y_pred_rfc_sk))
print(classification_report(y_te, y_pred_rfc_sk, target_names=["not fraud", "fraud"]))

accuracy: 0.9737321141308949
              precision    recall  f1-score   support

   not fraud       0.97      1.00      0.99     45584
       fraud       0.90      0.28      0.43      1660

    accuracy                           0.97     47244
   macro avg       0.94      0.64      0.71     47244
weighted avg       0.97      0.97      0.97     47244

Готовые реализации ансамблевых алгоритмов из sklearn дают результаты лишь на сотую долю хуже, чем собственные реализации, но при этом обучаются кратно быстрее.

### 5. Серия экспериментов с готовыми реализациями градиентного бустинга из sklearn, XGBoost, LightGBM и CatBoost

Посмотрим на результаты четырех различных реализаций градиентного бустинга и сравним их с результатами бэггинга и случайного леса.<br>
Будем подбирать следующие гиперпараметры: n_estimators - количество деревьев; max_depth - глубину одного дерева; min_samples_split вместе с min_samples_leaf - минимальное число объектов для разбиения и соотвественно минимальное число объектов в листе. Чтобы не усложнять эксперимент, пусть min_samples_split всегда в два раза больше min_samples_leaf.

Обучим готовый Gradient Boosting Classifier из sklearn на train data, предскажем значения для test data и оценим результаты.

In [17]:
MODEL_NAME = "SkGradientBoostingClassifier"

if "all_experiment_results" not in globals():
    all_experiment_results = []

def collect_metrics(y_true, y_pred, model_name, params):
    report = classification_report(
        y_true,
        y_pred,
        target_names=["not fraud", "fraud"],
        output_dict=True,
        zero_division=0
    )
    
    return {
        "model": model_name,
        "n_estimators": params["n_estimators"],
        "max_depth": params["max_depth"],
        "min_samples_leaf": params["min_samples_leaf"],
        "min_samples_split": params["min_samples_split"],
        "accuracy": accuracy_score(y_true, y_pred),
        "not fraud precision": report["not fraud"]["precision"],
        "not fraud recall": report["not fraud"]["recall"],
        "not fraud f1-score": report["not fraud"]["f1-score"],
        "fraud precision": report["fraud"]["precision"],
        "fraud recall": report["fraud"]["recall"],
        "fraud f1-score": report["fraud"]["f1-score"],
    }

gb_param_sets = [
    {"n_estimators": 5, "max_depth": 8, "min_samples_split": 30, "min_samples_leaf": 15},
    {"n_estimators": 50, "max_depth": 5, "min_samples_split": 40, "min_samples_leaf": 20},
    {"n_estimators": 100, "max_depth": 3, "min_samples_split": 60, "min_samples_leaf": 30},
]

gb_results = []

for i, params in enumerate(gb_param_sets, start=1):
    model = GradientBoostingClassifier(
        n_estimators=params["n_estimators"],
        max_depth=params["max_depth"],
        min_samples_split=params["min_samples_split"],
        min_samples_leaf=params["min_samples_leaf"],
        random_state=seed,
        verbose=1
    )
    
    model.fit(X_tr_processed, y_tr)
    y_pred = model.predict(X_te_processed)
    
    row = collect_metrics(
        y_true=y_te,
        y_pred=y_pred,
        model_name=MODEL_NAME,
        params=params
    )
    gb_results.append(row)

all_experiment_results = [r for r in all_experiment_results if r["model"] != MODEL_NAME]
all_experiment_results.extend(gb_results)

df_gb_results = pd.DataFrame(gb_results)
display(df_gb_results)

      Iter       Train Loss   Remaining Time
         1           0.2495            2.31m
         2           0.2374            1.73m
         3           0.2299            1.15m
         4           0.2241           34.59s
         5           0.2172            0.00s
      Iter       Train Loss   Remaining Time
         1           0.2613           17.77m
         2           0.2531           17.48m
         3           0.2449           17.09m
         4           0.2388           16.75m
         5           0.2328           16.38m
         6           0.2292           16.04m
         7           0.2258           15.67m
         8           0.2225           15.24m
         9           0.2194           14.86m
        10           0.2167           14.50m
        20           0.1989           10.82m
        30           0.1885            7.19m
        40           0.1823            3.60m
        50           0.1778            0.00s
      Iter       Train Loss   Remaining Time
         1           0.2724           21.50m
         2           0.2665           21.41m
         3           0.2603           21.15m
         4           0.2559           20.95m
         5           0.2519           20.70m
         6           0.2489           20.47m
         7           0.2448           20.28m
         8           0.2420           20.04m
         9           0.2392           19.85m
        10           0.2367           19.63m
        20           0.2186           17.43m
        30           0.2087           15.20m
        40           0.2036           13.05m
        50           0.1998           10.90m
        60           0.1963            8.71m
        70           0.1941            6.54m
        80           0.1919            4.36m
        90           0.1902            2.18m
       100           0.1882            0.00s

                          model  n_estimators  ...  fraud recall  fraud f1-score
0  SkGradientBoostingClassifier             5  ...      0.234940        0.377358
1  SkGradientBoostingClassifier            50  ...      0.346988        0.501305
2  SkGradientBoostingClassifier           100  ...      0.331928        0.482487

[3 rows x 12 columns]

Хорошие результаты (fraud f1-score за 0.5) требуют длительного времени обучения - в районе 20 минут на один большой ансамбль из слабых деревьев.

Обучим готовый Gradient Boosting Classifier из xgboost на train data, предскажем значения для test data и оценим результаты.

In [18]:
MODEL_NAME = "XGBClassifier"

if "all_experiment_results" not in globals():
    all_experiment_results = []

def collect_metrics(y_true, y_pred, model_name, params):
    report = classification_report(
        y_true,
        y_pred,
        target_names=["not fraud", "fraud"],
        output_dict=True,
        zero_division=0
    )
    
    return {
        "model": model_name,
        "n_estimators": params["n_estimators"],
        "max_depth": params["max_depth"],
        "min_samples_split": params["min_samples_split"],
        "min_samples_leaf": params["min_samples_leaf"],
        "accuracy": accuracy_score(y_true, y_pred),
        "not fraud precision": report["not fraud"]["precision"],
        "not fraud recall": report["not fraud"]["recall"],
        "not fraud f1-score": report["not fraud"]["f1-score"],
        "fraud precision": report["fraud"]["precision"],
        "fraud recall": report["fraud"]["recall"],
        "fraud f1-score": report["fraud"]["f1-score"],
    }

# Для XGBoost ближайший аналог min_samples_leaf — min_child_weight
xgb_param_sets = [
    {"n_estimators": 5, "max_depth": 8, "min_samples_split": 30, "min_samples_leaf": 15},
    {"n_estimators": 50, "max_depth": 5, "min_samples_split": 40, "min_samples_leaf": 20},
    {"n_estimators": 100, "max_depth": 3, "min_samples_split": 60, "min_samples_leaf": 30},
]

xgb_results = []

for i, params in enumerate(xgb_param_sets, start=1):
    model = XGBClassifier(
        n_estimators=params["n_estimators"],
        max_depth=params["max_depth"],
        min_child_weight=params["min_samples_leaf"],
        learning_rate=0.1,
        random_state=seed,
        n_jobs=32
    )
    
    model.fit(X_tr_processed, y_tr)
    y_pred = model.predict(X_te_processed)
    
    row = collect_metrics(
        y_true=y_te,
        y_pred=y_pred,
        model_name=MODEL_NAME,
        params=params
    )
    xgb_results.append(row)

all_experiment_results = [r for r in all_experiment_results if r["model"] != MODEL_NAME]
all_experiment_results.extend(xgb_results)

df_xgb_results = pd.DataFrame(xgb_results)
display(df_xgb_results)

           model  n_estimators  ...  fraud recall  fraud f1-score
0  XGBClassifier             5  ...      0.058434        0.110353
1  XGBClassifier            50  ...      0.328916        0.481906
2  XGBClassifier           100  ...      0.312048        0.463742

[3 rows x 12 columns]

Почти мгновенное обучение благодаря возможности распараллелить его, но fraud recall и вместе с ним fraud f1-score немного хуже, чем у реализации из sklearn.

Обучим готовый Gradient Boosting Classifier из lightgbm на train data, предскажем значения для test data и оценим результаты.

In [19]:
MODEL_NAME = "LGBMClassifier"

if "all_experiment_results" not in globals():
    all_experiment_results = []

def collect_metrics(y_true, y_pred, model_name, params):
    report = classification_report(
        y_true,
        y_pred,
        target_names=["not fraud", "fraud"],
        output_dict=True,
        zero_division=0
    )
    
    return {
        "model": model_name,
        "n_estimators": params["n_estimators"],
        "max_depth": params["max_depth"],
        "min_samples_split": params["min_samples_split"],
        "min_samples_leaf": params["min_samples_leaf"],
        "accuracy": accuracy_score(y_true, y_pred),
        "not fraud precision": report["not fraud"]["precision"],
        "not fraud recall": report["not fraud"]["recall"],
        "not fraud f1-score": report["not fraud"]["f1-score"],
        "fraud precision": report["fraud"]["precision"],
        "fraud recall": report["fraud"]["recall"],
        "fraud f1-score": report["fraud"]["f1-score"],
    }

# Для LightGBM ближайший аналог min_samples_leaf — min_child_samples
lgbm_param_sets = [
    {"n_estimators": 5, "max_depth": 8, "min_samples_split": 30, "min_samples_leaf": 15},
    {"n_estimators": 50, "max_depth": 5, "min_samples_split": 40, "min_samples_leaf": 20},
    {"n_estimators": 100, "max_depth": 3, "min_samples_split": 60, "min_samples_leaf": 30},
]

lgbm_results = []

for i, params in enumerate(lgbm_param_sets, start=1):
    model = LGBMClassifier(
        n_estimators=params["n_estimators"],
        max_depth=params["max_depth"],
        min_child_samples=params["min_samples_leaf"],
        learning_rate=0.1,
        random_state=seed,
        n_jobs=32,
        verbosity=1
    )
    
    model.fit(X_tr_processed, y_tr)
    y_pred = model.predict(X_te_processed)
    
    row = collect_metrics(
        y_true=y_te,
        y_pred=y_pred,
        model_name=MODEL_NAME,
        params=params
    )
    lgbm_results.append(row)

all_experiment_results = [r for r in all_experiment_results if r["model"] != MODEL_NAME]
all_experiment_results.extend(lgbm_results)

df_lgbm_results = pd.DataFrame(lgbm_results)
display(df_lgbm_results)

[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Info] Number of positive: 14939, number of negative: 410249
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.101159 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 34390
[LightGBM] [Info] Number of data points in the train set: 425188, number of used features: 435
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.035135 -> initscore=-3.312789
[LightGBM] [Info] Start training from score -3.312789
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Info] Number of positive: 14939, number of negative: 410249
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.106599 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 34387
[LightGBM] [Info] Number of data points in the train set: 425188, number of used features: 434
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.035135 -> initscore=-3.312789
[LightGBM] [Info] Start training from score -3.312789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Info] Number of positive: 14939, number of negative: 410249
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.092503 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 34387
[LightGBM] [Info] Number of data points in the train set: 425188, number of used features: 434
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.035135 -> initscore=-3.312789
[LightGBM] [Info] Start training from score -3.312789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

            model  n_estimators  ...  fraud recall  fraud f1-score
0  LGBMClassifier             5  ...      0.146386        0.253125
1  LGBMClassifier            50  ...      0.360843        0.515047
2  LGBMClassifier           100  ...      0.323494        0.475011

[3 rows x 12 columns]

Время обучения сопоставимо с очень быстрым XGBClassifier, при этом мы получили fraud f1-score = 0.52 за счет небольшого повышения fraud recall.

Обучим готовый Gradient Boosting Classifier из catboost на train data, предскажем значения для test data и оценим результаты.

In [20]:
MODEL_NAME = "CatBoostClassifier"

if "all_experiment_results" not in globals():
    all_experiment_results = []

def collect_metrics(y_true, y_pred, model_name, params):
    report = classification_report(
        y_true,
        y_pred,
        target_names=["not fraud", "fraud"],
        output_dict=True,
        zero_division=0
    )
    
    return {
        "model": model_name,
        "n_estimators": params["n_estimators"],
        "max_depth": params["max_depth"],
        "min_samples_split": params["min_samples_split"],
        "min_samples_leaf": params["min_samples_leaf"],
        "accuracy": accuracy_score(y_true, y_pred),
        "not fraud precision": report["not fraud"]["precision"],
        "not fraud recall": report["not fraud"]["recall"],
        "not fraud f1-score": report["not fraud"]["f1-score"],
        "fraud precision": report["fraud"]["precision"],
        "fraud recall": report["fraud"]["recall"],
        "fraud f1-score": report["fraud"]["f1-score"],
    }

# Для CatBoost используем depth и min_data_in_leaf
cat_param_sets = [
    {"n_estimators": 5, "max_depth": 8, "min_samples_split": 30, "min_samples_leaf": 15},
    {"n_estimators": 50, "max_depth": 5, "min_samples_split": 40, "min_samples_leaf": 20},
    {"n_estimators": 100, "max_depth": 3, "min_samples_split": 60, "min_samples_leaf": 30},
]

cat_results = []

for i, params in enumerate(cat_param_sets, start=1):
    model = CatBoostClassifier(
        iterations=params["n_estimators"],
        depth=params["max_depth"],
        min_data_in_leaf=params["min_samples_leaf"],
        learning_rate=0.1,
        thread_count=32,
        random_seed=seed,
        verbose=True
    )
    
    model.fit(X_tr_processed, y_tr)
    y_pred = model.predict(X_te_processed)
    y_pred = np.array(y_pred).astype(int).ravel()
    
    row = collect_metrics(
        y_true=y_te,
        y_pred=y_pred,
        model_name=MODEL_NAME,
        params=params
    )
    cat_results.append(row)

all_experiment_results = [r for r in all_experiment_results if r["model"] != MODEL_NAME]
all_experiment_results.extend(cat_results)

df_cat_results = pd.DataFrame(cat_results)
display(df_cat_results)

0:	learn: 0.5416353	total: 115ms	remaining: 461ms
1:	learn: 0.4233192	total: 172ms	remaining: 257ms
2:	learn: 0.3407956	total: 217ms	remaining: 145ms
3:	learn: 0.2837382	total: 260ms	remaining: 65ms
4:	learn: 0.2391227	total: 309ms	remaining: 0us
0:	learn: 0.5430243	total: 35ms	remaining: 1.72s
1:	learn: 0.4292405	total: 66.1ms	remaining: 1.59s
2:	learn: 0.3475419	total: 97.9ms	remaining: 1.53s
3:	learn: 0.2882067	total: 126ms	remaining: 1.45s
4:	learn: 0.2449676	total: 155ms	remaining: 1.39s
5:	learn: 0.2113430	total: 191ms	remaining: 1.4s
6:	learn: 0.1901430	total: 219ms	remaining: 1.35s
7:	learn: 0.1720840	total: 250ms	remaining: 1.31s
8:	learn: 0.1587281	total: 280ms	remaining: 1.27s
9:	learn: 0.1484111	total: 311ms	remaining: 1.24s
10:	learn: 0.1407966	total: 344ms	remaining: 1.22s
11:	learn: 0.1345493	total: 378ms	remaining: 1.2s
12:	learn: 0.1298617	total: 407ms	remaining: 1.16s
13:	learn: 0.1261715	total: 438ms	remaining: 1.13s
14:	learn: 0.1226042	total: 474ms	remaining: 1.11s
15:	learn: 0.1203490	total: 505ms	remaining: 1.07s
16:	learn: 0.1181290	total: 538ms	remaining: 1.04s
17:	learn: 0.1158424	total: 576ms	remaining: 1.02s
18:	learn: 0.1144728	total: 607ms	remaining: 990ms
19:	learn: 0.1125755	total: 643ms	remaining: 965ms
20:	learn: 0.1113144	total: 678ms	remaining: 937ms
21:	learn: 0.1107608	total: 706ms	remaining: 898ms
22:	learn: 0.1093456	total: 742ms	remaining: 871ms
23:	learn: 0.1086792	total: 773ms	remaining: 838ms
24:	learn: 0.1083034	total: 801ms	remaining: 801ms
25:	learn: 0.1075956	total: 842ms	remaining: 777ms
26:	learn: 0.1068031	total: 878ms	remaining: 748ms
27:	learn: 0.1059196	total: 915ms	remaining: 719ms
28:	learn: 0.1054031	total: 950ms	remaining: 688ms
29:	learn: 0.1049684	total: 983ms	remaining: 655ms
30:	learn: 0.1043577	total: 1.02s	remaining: 624ms
31:	learn: 0.1039110	total: 1.05s	remaining: 593ms
32:	learn: 0.1035681	total: 1.09s	remaining: 560ms
33:	learn: 0.1030474	total: 1.12s	remaining: 529ms
34:	learn: 0.1026926	total: 1.16s	remaining: 497ms
35:	learn: 0.1025069	total: 1.19s	remaining: 462ms
36:	learn: 0.1023112	total: 1.22s	remaining: 428ms
37:	learn: 0.1020157	total: 1.25s	remaining: 395ms
38:	learn: 0.1015121	total: 1.29s	remaining: 363ms
39:	learn: 0.1010837	total: 1.32s	remaining: 331ms
40:	learn: 0.1007582	total: 1.36s	remaining: 298ms
41:	learn: 0.1005437	total: 1.39s	remaining: 265ms
42:	learn: 0.1001740	total: 1.43s	remaining: 233ms
43:	learn: 0.1000125	total: 1.46s	remaining: 199ms
44:	learn: 0.0998323	total: 1.5s	remaining: 166ms
45:	learn: 0.0994663	total: 1.53s	remaining: 134ms
46:	learn: 0.0992961	total: 1.57s	remaining: 100ms
47:	learn: 0.0990674	total: 1.6s	remaining: 66.8ms
48:	learn: 0.0988609	total: 1.64s	remaining: 33.5ms
49:	learn: 0.0984446	total: 1.68s	remaining: 0us
0:	learn: 0.5442400	total: 29.5ms	remaining: 2.92s
1:	learn: 0.4322381	total: 54.5ms	remaining: 2.67s
2:	learn: 0.3521445	total: 78.8ms	remaining: 2.55s
3:	learn: 0.2934426	total: 104ms	remaining: 2.49s
4:	learn: 0.2493694	total: 130ms	remaining: 2.48s
5:	learn: 0.2182788	total: 155ms	remaining: 2.43s
6:	learn: 0.1944370	total: 179ms	remaining: 2.38s
7:	learn: 0.1782037	total: 203ms	remaining: 2.34s
8:	learn: 0.1655868	total: 228ms	remaining: 2.31s
9:	learn: 0.1546550	total: 253ms	remaining: 2.28s
10:	learn: 0.1477465	total: 277ms	remaining: 2.24s
11:	learn: 0.1414999	total: 300ms	remaining: 2.2s
12:	learn: 0.1365299	total: 324ms	remaining: 2.17s
13:	learn: 0.1327637	total: 351ms	remaining: 2.16s
14:	learn: 0.1288850	total: 376ms	remaining: 2.13s
15:	learn: 0.1265438	total: 401ms	remaining: 2.11s
16:	learn: 0.1241969	total: 427ms	remaining: 2.08s
17:	learn: 0.1223309	total: 451ms	remaining: 2.06s
18:	learn: 0.1206574	total: 475ms	remaining: 2.02s
19:	learn: 0.1193385	total: 507ms	remaining: 2.03s
20:	learn: 0.1180016	total: 532ms	remaining: 2s
21:	learn: 0.1171869	total: 559ms	remaining: 1.98s
22:	learn: 0.1161505	total: 584ms	remaining: 1.96s
23:	learn: 0.1156720	total: 607ms	remaining: 1.92s
24:	learn: 0.1149858	total: 631ms	remaining: 1.89s
25:	learn: 0.1143713	total: 656ms	remaining: 1.87s
26:	learn: 0.1136411	total: 681ms	remaining: 1.84s
27:	learn: 0.1129631	total: 706ms	remaining: 1.81s
28:	learn: 0.1125880	total: 729ms	remaining: 1.78s
29:	learn: 0.1121804	total: 752ms	remaining: 1.75s
30:	learn: 0.1115645	total: 778ms	remaining: 1.73s
31:	learn: 0.1110552	total: 806ms	remaining: 1.71s
32:	learn: 0.1108176	total: 829ms	remaining: 1.68s
33:	learn: 0.1104490	total: 853ms	remaining: 1.66s
34:	learn: 0.1101863	total: 879ms	remaining: 1.63s
35:	learn: 0.1094522	total: 912ms	remaining: 1.62s
36:	learn: 0.1092982	total: 937ms	remaining: 1.59s
37:	learn: 0.1089065	total: 966ms	remaining: 1.57s
38:	learn: 0.1086070	total: 993ms	remaining: 1.55s
39:	learn: 0.1084269	total: 1.02s	remaining: 1.52s
40:	learn: 0.1081038	total: 1.05s	remaining: 1.51s
41:	learn: 0.1078547	total: 1.07s	remaining: 1.48s
42:	learn: 0.1076401	total: 1.1s	remaining: 1.46s
43:	learn: 0.1072902	total: 1.12s	remaining: 1.43s
44:	learn: 0.1070105	total: 1.15s	remaining: 1.41s
45:	learn: 0.1067002	total: 1.18s	remaining: 1.38s
46:	learn: 0.1062254	total: 1.21s	remaining: 1.36s
47:	learn: 0.1060986	total: 1.23s	remaining: 1.34s
48:	learn: 0.1058649	total: 1.26s	remaining: 1.32s
49:	learn: 0.1057278	total: 1.29s	remaining: 1.29s
50:	learn: 0.1054756	total: 1.32s	remaining: 1.26s
51:	learn: 0.1053637	total: 1.34s	remaining: 1.24s
52:	learn: 0.1052816	total: 1.37s	remaining: 1.21s
53:	learn: 0.1051123	total: 1.4s	remaining: 1.19s
54:	learn: 0.1048085	total: 1.42s	remaining: 1.17s
55:	learn: 0.1045441	total: 1.45s	remaining: 1.14s
56:	learn: 0.1043490	total: 1.48s	remaining: 1.11s
57:	learn: 0.1042083	total: 1.5s	remaining: 1.09s
58:	learn: 0.1039410	total: 1.53s	remaining: 1.06s
59:	learn: 0.1038502	total: 1.56s	remaining: 1.04s
60:	learn: 0.1037461	total: 1.58s	remaining: 1.01s
61:	learn: 0.1035537	total: 1.61s	remaining: 986ms
62:	learn: 0.1034281	total: 1.63s	remaining: 959ms
63:	learn: 0.1031460	total: 1.66s	remaining: 935ms
64:	learn: 0.1030313	total: 1.69s	remaining: 908ms
65:	learn: 0.1029225	total: 1.71s	remaining: 881ms
66:	learn: 0.1028638	total: 1.74s	remaining: 855ms
67:	learn: 0.1025433	total: 1.77s	remaining: 831ms
68:	learn: 0.1024605	total: 1.79s	remaining: 805ms
69:	learn: 0.1023390	total: 1.82s	remaining: 779ms
70:	learn: 0.1022041	total: 1.84s	remaining: 752ms
71:	learn: 0.1019034	total: 1.87s	remaining: 728ms
72:	learn: 0.1017988	total: 1.9s	remaining: 702ms
73:	learn: 0.1017035	total: 1.92s	remaining: 676ms
74:	learn: 0.1015126	total: 1.97s	remaining: 658ms
75:	learn: 0.1013372	total: 2s	remaining: 633ms
76:	learn: 0.1012624	total: 2.06s	remaining: 614ms
77:	learn: 0.1011353	total: 2.08s	remaining: 588ms
78:	learn: 0.1010243	total: 2.14s	remaining: 569ms
79:	learn: 0.1008598	total: 2.18s	remaining: 545ms
80:	learn: 0.1007452	total: 2.21s	remaining: 518ms
81:	learn: 0.1005585	total: 2.24s	remaining: 491ms
82:	learn: 0.1004868	total: 2.26s	remaining: 463ms
83:	learn: 0.1004400	total: 2.29s	remaining: 436ms
84:	learn: 0.1002812	total: 2.31s	remaining: 408ms
85:	learn: 0.1002020	total: 2.34s	remaining: 381ms
86:	learn: 0.1000825	total: 2.36s	remaining: 353ms
87:	learn: 0.0998911	total: 2.39s	remaining: 326ms
88:	learn: 0.0998304	total: 2.42s	remaining: 299ms
89:	learn: 0.0997680	total: 2.44s	remaining: 271ms
90:	learn: 0.0996278	total: 2.46s	remaining: 244ms
91:	learn: 0.0995308	total: 2.49s	remaining: 217ms
92:	learn: 0.0994654	total: 2.52s	remaining: 189ms
93:	learn: 0.0993198	total: 2.54s	remaining: 162ms
94:	learn: 0.0992373	total: 2.56s	remaining: 135ms
95:	learn: 0.0991865	total: 2.59s	remaining: 108ms
96:	learn: 0.0990922	total: 2.62s	remaining: 81ms
97:	learn: 0.0990252	total: 2.65s	remaining: 54ms
98:	learn: 0.0989058	total: 2.67s	remaining: 27ms
99:	learn: 0.0988418	total: 2.69s	remaining: 0us

                model  n_estimators  ...  fraud recall  fraud f1-score
0  CatBoostClassifier             5  ...      0.170482        0.287164
1  CatBoostClassifier            50  ...      0.286145        0.434982
2  CatBoostClassifier           100  ...      0.292771        0.440417

[3 rows x 12 columns]

За счет падения fraud recall значения fraud f1-score немного ниже, чем у остальных реализаций.

In [21]:
# собираем все результаты в одну таблицу
df_all_experiments = pd.DataFrame(all_experiment_results)

# ссылка на таблицу
SPREADSHEET_URL = "https://docs.google.com/spreadsheets/d/1IQ3mcvYhSJPAtBuFSWnYujqZOgYWL09CcKgEvnOr26U/edit#gid=0"

# доступы
SCOPES = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive",
]

TOKEN_FILE = "token.json"

creds = None

# пытаемся загрузить токен
if os.path.exists(TOKEN_FILE):
    creds = Credentials.from_authorized_user_file(TOKEN_FILE, SCOPES)

# если токен протух
if creds and creds.expired and creds.refresh_token:
    creds.refresh(Request())

# если токена нет - логинимся
if not creds or not creds.valid:
    flow = InstalledAppFlow.from_client_secrets_file("credentials.json", SCOPES)
    flow.redirect_uri = "urn:ietf:wg:oauth:2.0:oob"
    auth_url, _ = flow.authorization_url(prompt="consent")
    print("Открой эту ссылку:")
    print(auth_url)
    code = input("Вставь полученный по ссылке код: ")
    flow.fetch_token(code=code)
    creds = flow.credentials
    # сохраняем токен
    with open(TOKEN_FILE, "w") as f:
        f.write(creds.to_json())

# входим и подключаемся к таблице
gc = gspread.authorize(creds)
sh = gc.open_by_url(SPREADSHEET_URL)
worksheet = sh.sheet1

# запись результатов в Google Таблицу
columns_order = [
    "model",
    "n_estimators",
    "max_depth",
    "min_samples_split",
    "min_samples_leaf",
    "accuracy",
    "not fraud precision",
    "not fraud recall",
    "not fraud f1-score",
    "fraud precision",
    "fraud recall",
    "fraud f1-score",
]
df_to_upload = df_all_experiments[columns_order].copy().round(2)
data = df_to_upload.values.tolist()
worksheet.batch_clear(["A9:L20"])
worksheet.update(range_name="A9", values=data)

print("Результаты экспериментов успешно записаны в Google Таблицу!")

Результаты экспериментов успешно записаны в Google Таблицу!

Результаты экспериментов, сведенные в таблицу: https://docs.google.com/spreadsheets/d/1IQ3mcvYhSJPAtBuFSWnYujqZOgYWL09CcKgEvnOr26U/edit?gid=0#gid=0<br>
Из таблицы видно, что собственные реализации бэггинга и рандомного леса по качеству не уступают реализациям из sklearn, однако важное примечание - они обучаются значительно дольше.<br>
Все готовые реализации градиентного бустинга с маленьким количеством деревьев в ансамбле очень сильно теряют fraud recall, зато они в основном быстро обучаются ансамблями по 50-100 слабых деревьев и тогда начинают давать fraud f1-score выше, чем у бэггинга и рандомного леса.<br>
С общим accuracy, not fraud объектами и fraud precision ни у кого проблем нет - все эти метрики в районе 0.9, поэтому при выборе модели будем смотреть на fraud f1-score.

Самый лучший результат у LGBM Classifier - f1-score = 0.52 для fraud при 50 деревьях глубиной 5. Тогда возьмем именно эту модель машинного обучения для формирования предсказаний.

### 6. Создание таблицы с предсказаниями для test_public.csv

Итак, выбранная модель - LGBM Classifier. Она очень быстро обучается, поэтому можно еще подкрутить ей параметры, чтобы огромный ансамбль сильных деревьев дал результаты получше.

In [22]:
lgbmc = LGBMClassifier(n_estimators=5000, max_depth=8, min_child_samples=30, learning_rate=0.1, random_state=seed, n_jobs=32, verbosity=1).fit(X_tr_processed, y_tr)
y_pred_lgbmc = lgbmc.predict(X_te_processed)

print("accuracy:", accuracy_score(y_te, y_pred_lgbmc))
print(classification_report(y_te, y_pred_lgbmc, target_names=["not fraud", "fraud"]))

[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Info] Number of positive: 14939, number of negative: 410249
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.108418 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 34387
[LightGBM] [Info] Number of data points in the train set: 425188, number of used features: 434
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.035135 -> initscore=-3.312789
[LightGBM] [Info] Start training from score -3.312789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
accuracy: 0.9886969773939548
              precision    recall  f1-score   support

   not fraud       0.99      1.00      0.99     45584
       fraud       0.98      0.69      0.81      1660

    accuracy                           0.99     47244
   macro avg       0.99      0.84      0.90     47244
weighted avg       0.99      0.99      0.99     47244

Огромный ансамбль глубоких деревьев поднял fraud recall и мы получили fraud f1-score = 0.81. Теперь обученной моделью дадим предсказания для test public и сохраним их в csv-файл.

In [23]:
# путь к test_public
file_test_path = os.path.join(dataset_path, "test_public.csv")
# загрузка csv-файла
df_test = pd.read_csv(file_test_path)

# предобработка данных пайплайном
X_test_processed = pipeline.transform(df_test)

# вероятности fraud
test_proba_lgbmc = lgbmc.predict_proba(X_test_processed)[:, 1]

# формирование итоговой таблицы
result = pd.DataFrame({"TransactionID": df_test["TransactionID"], "isFraud": test_proba_lgbmc})

# сохранение
output_path = os.path.join("/home/jupyter/project/ml-2026-spring-hw-03-superkroshki/", "classification_submission.csv")
result.to_csv(output_path, index=False, sep=';', float_format='%.8f')

print("Сохранено в:", output_path)

[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
Сохранено в: /home/jupyter/project/ml-2026-spring-hw-03-superkroshki/classification_submission.csv